---
- hosts: localhost
  name: Sync local repository

  vars_files:
    - vars.yml

  vars:
    password_store_dir: "{{ lookup('env', 'PASSWORD_STORE_DIR', default=ansible_user_dir + '/.password-store') }}"

  tasks:
    - name: Ensure ssh-ability
      command:
        cmd: pressh {{ geheim_hoster }}

    - name: Git sync
      shell:
        cmd: |
          git pull -r
          git push
      args:
        chdir: '{{ password_store_dir }}'
...
