---
- hosts: localhost
  name: Cleanup local known hosts

  vars_files:
    - sync_vars.yml

  tasks:
    - name: Ensure SSH-ability
      command:
        cmd: pressh {{ geheim_hoster }}

- hosts: geheim_mgt
  name: Initialise the server with the repository
  remote_user: '{{ geheim_ssh_user }}'

  vars_files:
    - sync_vars.yml

  vars:
    encryption_passphrase_lookup_key: '{{ password_lookup_key }}'
    encryption_passphrase: "{{ lookup('passwordstore', encryption_passphrase_lookup_key) }}"
    password_store_dir: "{{ lookup('env', 'PASSWORD_STORE_DIR', default=ansible_user_dir + '/.password-store') }}"
    wait_var: GEHEIM_WAIT

  tasks:
    - name: Add the user
      user:
        name: '{{ repo_user_name }}'
        shell: /bin/bash
      become: yes

    - name: Get public keys from GitHub
      uri:
        url: https://api.github.com/users/{{ github_username }}/keys
        return_content: yes
        body_format: json
      register: github_public_keys

    - name: Add authorized keys
      authorized_key:
        key: '{{ item.key }}'
        user: '{{ repo_user_name }}'
      loop: '{{ github_public_keys.json }}'
      become: yes

    - name: Install required packages
      package:
        name:
          - cryptsetup
          - git
      become: yes

    - name: Save the key file
      lineinfile:
        path: '{{ keyfile_path }}'
        create: yes
        owner: root
        group: root
        mode: '0400'
        line: '{{ encryption_passphrase }}'
      become: yes
      tags: volume-ready

    - name: Remove new line character from the key file
      replace:
        path: '{{ keyfile_path }}'
        regexp: '\n'
        replace: ''
      become: yes
      tags: volume-ready

    - name: Open the device
      command: cryptsetup open {{ device_path }} {{ mapping_name }} --key-file {{ keyfile_path }}
      become: yes
      args:
        creates: '/dev/mapper/{{ mapping_name }}'
      tags: volume-ready

    - name: Shred the key file
      command: shred '{{ keyfile_path }}'
      become: yes

    - name: Remove the key file
      file:
        path: '{{ keyfile_path }}'
        state: absent
      become: yes

    - name: Initialize the mount path
      file:
        path: '{{ absolute_mount_path }}'
        state: directory
        owner: '{{ repo_user_name}}'
        group: '{{ repo_user_name}}'
      become: yes

    - name: Mount the device
      mount:
        src: '{{ device_mapped_path }}'
        path: '{{ absolute_mount_path }}'
        fstype: ext4
        state: mounted
      become: yes

    - name: Make sure user ownership is correct
      file:
        state: directory
        path: '{{ absolute_mount_path }}'
        owner: '{{ repo_user_name }}'
        group: '{{ repo_user_name }}'
        recurse: yes
      become: yes

    - name: Git sync
      shell: |
        git pull -r
        git push
      args:
        chdir: '{{ password_store_dir }}'
      delegate_to: localhost

    - name: Show notification
      command: notify-send '{{ ansible_play_name }}' 'Ready for sync'
      delegate_to: localhost
      when: lookup('env', wait_var)

    - pause:
        prompt: Continue when the sync has been done
      when: lookup('env', wait_var)

    - name: Post git sync
      shell: |
        git pull -r
        git push
      args:
        chdir: '{{ password_store_dir }}'
      delegate_to: localhost
      when: lookup('env', wait_var)

    - name: Sync disks
      command: sync
      become: yes

    - name: Unmount the device
      mount:
        path: '{{ absolute_mount_path }}'
        state: unmounted
      become: yes

    - name: Close the device
      command: cryptsetup close {{ mapping_name }}
      become: yes
...
