---
- hosts: geheim_mgt
  name: Initialize the volume
  become: yes

  vars:
    device_path: "/dev/{{ (ansible_devices.keys() | sort)[-1] }}"
    device_partition: 1

  vars_files:
    - sync_vars.yml

  tasks:
    - name: Create a partition
      parted:
        device: '{{ device_path }}'
        number: '{{ device_partition }}'
        state: present

    - name: Copy key file
      copy:
        dest: '{{ keyfile_path }}'
        content: "{{ lookup('passwordstore', password_lookup_key) }}"

    - name: Install cryptsetup
      package:
        name: cryptsetup

    - name: Encrypt the volume with LUKS
      shell: echo YES | cryptsetup luksFormat {{ device_path }} --key-file {{ keyfile_path }}

    - name: Create the mapping
      command: cryptsetup open {{ device_path }} {{ mapping_name }} --key-file {{ keyfile_path }}

    - name: Create the filesystem
      command: mkfs.ext4 {{ device_mapped_path }}

    - name: Remove the mapping
      command: cryptsetup close {{ mapping_name }}

    - name: Shred key file
      command: shred {{ keyfile_path }}

    - name: Remove key file
      file:
        path: '{{ keyfile_path }}'
        state: absent
...
