---
- hosts: localhost
  name: Sync local repository

  vars_files:
    - sync_vars.yml

  tasks:
    - name: Remove existing known host(s)
      known_hosts:
        name: '{{ geheim_hoster }}'
        state: absent

    - name: Wait until DNS is resolving
      command: host {{ geheim_hoster }}
      register: geheim_ip
      retries: 10
      delay: 60
      until: geheim_ip.rc == 0

    - name: Remove host keys for IPs of previous instances
      lineinfile:
        path: '{{ ansible_user_dir }}/.ssh/known_hosts'
        regexp: '^{{ geheim_ip.stdout.split()[-1] }} .*'
        state: absent

    - name: Add keys for host
      shell: ssh-keyscan {{ geheim_hoster }} | grep ecdsa-sha2-nistp256 >> '{{ ansible_user_dir }}/.ssh/known_hosts'

    - name: Git sync
      shell: |
        git pull -r
        git push
      args:
        chdir: '{{ ansible_user_dir }}/.password-store'
...
